export const customers = [
  {
    id: 'CUST001',
    name: 'Liam Johnson',
    email: 'liam@example.com',
    phone: '555-0101',
    totalSpent: 150.75,
    avatar: 'https://picsum.photos/seed/1/40/40',
  },
  {
    id: 'CUST002',
    name: 'Olivia Smith',
    email: 'olivia@example.com',
    phone: '555-0102',
    totalSpent: 205.5,
    avatar: 'https://picsum.photos/seed/2/40/40',
  },
  {
    id: 'CUST003',
    name: 'Noah Williams',
    email: 'noah@example.com',
    phone: '555-0103',
    totalSpent: 99.99,
    avatar: 'https://picsum.photos/seed/3/40/40',
  },
  {
    id: 'CUST004',
    name: 'Emma Brown',
    email: 'emma@example.com',
    phone: '555-0104',
    totalSpent: 312.0,
    avatar: 'https://picsum.photos/seed/4/40/40',
  },
  {
    id: 'CUST005',
    name: 'Ava Jones',
    email: 'ava@example.com',
    phone: '555-0105',
    totalSpent: 75.25,
    avatar: 'https://picsum.photos/seed/5/40/40',
  },
  {
    id: 'CUST006',
    name: 'William Garcia',
    email: 'william@example.com',
    phone: '555-0106',
    totalSpent: 500.0,
    avatar: 'https://picsum.photos/seed/6/40/40',
  },
  {
    id: 'CUST007',
    name: 'Sophia Miller',
    email: 'sophia@example.com',
    phone: '555-0107',
    totalSpent: 230.9,
    avatar: 'https://picsum.photos/seed/7/40/40',
  },
];

export const products = [
  {
    id: 'PROD001',
    name: 'Espresso',
    sku: 'SKU-ESP-01',
    price: 2.99,
    stock: 100,
    category: 'Coffee',
  },
  {
    id: 'PROD002',
    name: 'Latte',
    sku: 'SKU-LAT-01',
    price: 4.5,
    stock: 75,
    category: 'Coffee',
  },
  {
    id: 'PROD003',
    name: 'Croissant',
    sku: 'SKU-CRO-01',
    price: 3.25,
    stock: 50,
    category: 'Pastry',
  },
  {
    id: 'PROD004',
    name: 'Iced Tea',
    sku: 'SKU-TEA-01',
    price: 3.0,
    stock: 80,
    category: 'Beverage',
  },
  {
    id: 'PROD005',
    name: 'Blueberry Muffin',
    sku: 'SKU-MUF-01',
    price: 3.5,
    stock: 40,
    category: 'Pastry',
  },
  {
    id: 'PROD006',
    name: 'Cappuccino',
    sku: 'SKU-CAP-01',
    price: 4.5,
    stock: 65,
    category: 'Coffee',
  },
  {
    id: 'PROD007',
    name: 'Sandwich',
    sku: 'SKU-SAN-01',
    price: 8.99,
    stock: 20,
    category: 'Food',
  },
  {
    id: 'PROD008',
    name: 'Orange Juice',
    sku: 'SKU-OJ-01',
    price: 4.0,
    stock: 90,
    category: 'Beverage',
  },
];

export const transactions = [
  {
    id: 'TRN001',
    customerName: 'Liam Johnson',
    amount: 7.49,
    date: '2023-10-27T10:00:00Z',
    status: 'Paid',
    type: 'Sale',
  },
  {
    id: 'TRN002',
    customerName: 'Olivia Smith',
    amount: 4.5,
    date: '2023-10-27T10:15:00Z',
    status: 'Paid',
    type: 'Sale',
  },
  {
    id: 'TRN003',
    customerName: 'Noah Williams',
    amount: 3.25,
    date: '2023-10-27T10:30:00Z',
    status: 'Paid',
    type: 'Sale',
  },
  {
    id: 'TRN004',
    customerName: 'Emma Brown',
    amount: -4.5,
    date: '2023-10-27T11:00:00Z',
    status: 'Refunded',
    type: 'Refund',
  },
  {
    id: 'TRN005',
    customerName: 'Ava Jones',
    amount: 11.99,
    date: '2023-10-27T11:30:00Z',
    status: 'Paid',
    type: 'Sale',
  },
  {
    id: 'TRN006',
    customerName: 'Anonymous',
    amount: 2.99,
    date: '2023-10-27T12:00:00Z',
    status: 'Paid',
    type: 'Sale',
  },
];

export const inventory = products.map((product) => ({
  id: product.id,
  name: product.name,
  sku: product.sku,
  stock: product.stock,
  status: product.stock > 20 ? 'In Stock' : product.stock > 0 ? 'Low Stock' : 'Out of Stock',
}));

export const salesData = [
  { name: 'Jan', sales: 4000 },
  { name: 'Feb', sales: 3000 },
  { name: 'Mar', sales: 5000 },
  { name: 'Apr', sales: 4500 },
  { name: 'May', sales: 6000 },
  { name: 'Jun', sales: 5500 },
  { name: 'Jul', sales: 7000 },
  { name: 'Aug', sales: 6500 },
  { name: 'Sep', sales: 7500 },
  { name: 'Oct', sales: 8000 },
  { name: 'Nov', sales: 9000 },
  { name: 'Dec', sales: 8500 },
];
